workspace/second/src/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Modules</relationshipLabel>
        <relationshipName>Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace/second/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace/TestPG/src/classes/controllermethod.cls
public class controllermethod 
{
   public  Project__c newproj{get;set;}
   public Module__c  module{get;set;}
public List<Module__c> moduleList{get;set;}

    public controllermethod()
    {
        moduleList=new List<Module__c>();
         newproj = new Project__c();
         module=new Module__c();
         moduleList.add(module);
    }
    public PageReference closePopup() 
    {
        return null;
    }

    public PageReference Add(){ 
    Module__c module=new Module__c(); 
    moduleList.add(module); 
    return null;
    }
    /*
  public void Add()
  { 

      Module__c module=new Module__c(); 
      moduleList.add(module); 
  }
*/
    public PageReference savecreatenew() 
    {
        insert  newproj; 
        for (Module__c module :moduleList) {
            module.Project__c = String.valueOf(newproj.get('Id'));
        } 
        insert moduleList; 

    module.clear();
    moduleList.clear();
    newproj.clear() ;
        return null;
    }


}